### ISSUE TITLE
Categoria e Sub-Categoria

### ISSUE THREAD

**Issue by ramonruanxc** [ColmeiaSolucoes/nectarcrm-api#1]
Boa tarde,

Gostaria de me informar do seguinte.

Preciso cadastrar as categorias e sub categorias, só consigo ver na documentação que se eu enviar como um objeto já dentro do JSON, teoricamente ele irá ser inserido, mas como consigo inserir ele de forma desacoplada, como contatos, e me referindo aos produtos, por exemplo.

Quando acesso somente categoria, como está contida aqui : https://github.com/ColmeiaSolucoes/nectarcrm-api/tree/master/docs/categoria

Ele mostra relação somente com Contatos.

**Comment by ColmeiaSolucoes** [comment]
Boa tarde,

O end-point que você queria não existia. Portanto, criamos ele nesse momento, por favor verifique se atende os requisitos pedidos:

**End-point de categoria de produto**
[](https://github.com/ColmeiaSolucoes/nectarcrm-api/blob/master/docs/produtoCategoria)

**End-point de sub categoria de produto**
[](https://github.com/ColmeiaSolucoes/nectarcrm-api/blob/master/docs/produtoSubCategoria)
