### ISSUE TITLE
Erro 500 ao tentar criar oportunidades

### ISSUE THREAD

**Issue by agaabrieel** [ColmeiaSolucoes/nectarcrm-api#10]
Método post retorna

<!doctype html><html lang="pt"><head><title>HTTP Status 500 \xe2\x80\x93 Internal Server Error</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 \xe2\x80\x93 Internal Server Error</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Internal Server Error</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><hr class="line" /><h3>Apache Tomcat/9.0.33</h3></body></html>

**Comment by rmarques90** [comment]
Olá!

Qual o corpo da requisição e o endpoint que foi realizada a chamada? Pode ser que tenha algum parâmetro inválido.

**Comment by agaabrieel** [comment]
Endpoint é 'https://app.nectarcrm.com.br/crm/api/1/oportunidades'. Testei somente com header contendo o token de autenticação, com body vazio, com um único campo e até mesmo com header vazio. Todos com o mesmo problema.

**Comment by agaabrieel** [comment]
Algum update a respeito?

**Comment by rmarques90** [comment]
Olá!

Você precisa passar um corpo válido com, ao menos, um nome, cliente e um funil de venda.

```json
{ 
    "nome"': "Oportunidade teste",
    "cliente": {
        "id:" 123
    },
    "funilVenda": {
         "id": 456
    }
}
```

**Comment by agaabrieel** [comment]
@rmarques90, encontrei o problema. Vou detalhar aqui pra caso alguém passe por isso novamente:

A conta para a qual estou fazendo as requisições possui alguns campos personalizados obrigatórios. Quando fazia as requisições contendo somente os campos exigidos pela API, o servidor me retornava - como esperado - que alguns dos campos obrigatórios não foram preenchidos. Quando os incluia, a resposta era o código 500 mencionado.

O problema estava no fato de que um desses campos personalizados (e obrigatório) possuía um nome similar a um dos campos nativos do endpoint de oportunidades (produto vs produtos, respectivamente), o que fez com que eu informasse no corpo da requisição o campo produtos (uma array de objetos) e não o campo personalizado, uma string.
