### ISSUE TITLE
Api /proposta não está funcionando 

### ISSUE THREAD

**Issue by Hudson3384** [ColmeiaSolucoes/nectarcrm-api#11]
tentei realizar a chamada de proposta mas retorna um html dando 500 
```bash
curl 'https://app.nectarcrm.com.br/crm/api/1/propostas/?api_token={{mytoken}}&page=1&displayLength=50'
```
Nem assim:
```bash
curl 'https://app.nectarcrm.com.br/crm/api/1/proposta/?api_token={{mytoken}}&page=1&displayLength=50'
```
Tentei filtrar por oportunidade mas ocorre o mesmo resultado

**Comment by rafaelgondim** [comment]
O endpoint correto para listagem de proposta é esse:
`https://app.nectarcrm.com.br/crm/api/1/proposta/opportunity/[id da oportunidade]?api_token={{mytoken}}&page=1&displayLength=50'`
Vou remover o outro da documentação para evitar confusão.

**Comment by Hudson3384** [comment]
Opa, Muito obrigado !!!
