### ISSUE TITLE
/oportunidade envia somente oportunidades em andamento 

### ISSUE THREAD

**Issue by Hudson3384** [ColmeiaSolucoes/nectarcrm-api#13]
Realizando a endpoint /oportunidade ou /oportunidades, todas as oportunidades que retornam são status=1 independente da página. aplicando o filtro status=1,2,3,4,5 consegui pegar de geral 

Infomei só para caso de ser um bug, caso não seja, seria interessante informar desta particularidade na documentação

**Comment by rafaelgondim** [comment]
SIm, é isso mesmo, coloquei uma observação, como sugerido.
