### ISSUE TITLE
/publicacao limita a quantidade de páginas a 100

### ISSUE THREAD

**Issue by Hudson3384** [ColmeiaSolucoes/nectarcrm-api#14]
Eu gostaria de validar se essa limitação é proposital e se teria uma forma de pegar todas as publicações já que esta endpoint está limitada

**Comment by rafaelgondim** [comment]
Sim é proposital, é um cenario incomum. O ideal é você aplicar alguns filtros, como sistema=false, para não pegar as mensagens padrões geradas pelo Nectar.
