### ISSUE TITLE
Duplicata: endpoint de Propostas 

### ISSUE THREAD

**Issue by Hudson3384** [ColmeiaSolucoes/nectarcrm-api#17]
Olá prezados, estou abrindo uma outra issue por não ter tido retorno na anterior e talvez a razão tenha sido que não fui muito claro. 

Eu preciso de conseguir pegar as propostas. 
Devido ao /propostas não funcionar, estou tendo que puxar a lista de propostas de cada oportunidade que tenha ou não propostas e isso está gastando muitas requisições, me fazendo chegar perto da cota. 

Por isto, eu necessito, ou da volta do /propostas ou algum parâmetro em oportunidade para saber se a oportunidade contém propostas ou não

**Comment by rafaelgondim** [comment]
Entendi, estou adicionando a propriedade `qtdPropostas` no retorno da consulta da oportunidade (`/crm/api/1/oportunidade`). Deve estar disponivel na próxima versão.

**Comment by rafaelgondim** [comment]
Bom dia, essa alteração entrou junto de uma versão com novas funcionalidades que ainda está sendo validada pelo time de QA. Mas acredito que no máximo mais uma semana ela está online para todos.

**Comment by Hudson3384** [comment]
Obrigado pela colaboração, a OPEN DATACENTER agradece !!!
