### ISSUE TITLE
Erro 403

### ISSUE THREAD

**Issue by vittorbraga** [ColmeiaSolucoes/nectarcrm-api#2]
Olá, estou recebendo o erro 403, porém o meu token está correto.

O que devo verificar para saber o que está me retornado 403?

Tem limite de requisições em um espaço de tempo?

**Comment by ColmeiaSolucoes** [comment]
403 significa conflict, access denied, etc...
o que, no nosso caso, está ligado a campo obrigatório que não foi preenchido
