### ISSUE TITLE
filtro de status no endpoint de 'qualificacoes'

### ISSUE THREAD

**Issue by eduardoborgesgouveia** [ColmeiaSolucoes/nectarcrm-api#9]
Bom dia prezados,

Ao extrair os dados dos endpoints de oportunidades e qualificações, eu percebi que é necessário declarar (na requisição) o status do lead/oportunidade que se deseja. 

Em oportunidades, caso não seja explicitamente declarado na requisição, apenas as oportunidades com status = 1 (Em andamento) são retornados. Dessa maneira devemos explicitamente buscar por todos os status  (1 = Em andamento, 2 = Ganha, 3 = Perdida, 4 = Cancelada, 5 = Prorrogada).

Em qualificações (como em oportunidades) somente os leads com status 1 (Em andamento) são retornados, entretanto ao adicionar o parâmetro de status na requisição, não retorna dado algum, mesmo no sistema contendo dados de qualificações com diversos status.

Me parece haver algum problema na filtragem por status das APIs ou eu não estou sabendo fazer a requisição corretamente, vocês podem me auxiliar?

**Comment by rmarques90** [comment]
Olá Eduardo! Tudo bom?

Você pode passar um parâmetro chamado `ignoreStatus=true` para retornar de todas os status. Caso deseje de um status específico pode utilizar o parâmetro `faseId=`, onde pode passar individualmente e requisitar um a um:

- Andamento = 1;
- Agendamento (quando o funil houver etapa de agendamento) = 2; 
- Qualificada = 3;
- Descartada = 4;
- Vendida = 5; 
- Não vendida = 6;

Precisa de mais alguma coisa? =)

**Comment by eduardoborgesgouveia** [comment]
Muitíssimo obrigado Rafael, resolveu meu problema aqui e agora está tudo certo!
